Partie 1 : Listes Python vs tableaux NumPy 
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 
1) Créer une liste Python stockant ces températures; 
2) Créer un tableau NumPy équivalent stockant ces températures ; 
3) Effectuer une multiplication par 2 sur ces deux collections; 
4) Quelle différence observe-t-on ? 

In [94]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [95]:
import numpy as np

1.CREATION DE LISTE PYTHON 

In [96]:
Liste_temperature = [24.5 , 25.1 , 26.3 , 27.0 , 25.8 ]


2.CREATION DE TABLEAU NUMPY

In [97]:
tab_temp=np.array(Liste_temperature)

3.MULTIPLICATION DES DEUX PAR "2"

In [98]:
Liste_temperature= Liste_temperature*2
print(Liste_temperature)

tab_temp=tab_temp*2
print(tab_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


4.OBSERVATION

La différence observée se situe principalement au niveau des résultats. La multiplication par 2 double la liste et donne un tableau où chaque élément est multiplié par 2.


Partie 2 – Création des données 
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 
2) Créer un tableau contenant 10 valeurs égales à 1. 
3) Créer un tableau de 10 valeurs initialisées à 25. 
4) Créer une matrice identité de taille 5 × 5. 
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

1. Creer un tableau representant les mesures de température de 10 capteurs , initialement à zero


In [99]:
tab_zero=np.zeros(10)
print(tab_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.Créer un tableau contenant 10 valeurs égales à 1. 

In [100]:
tab_one=np.ones(10)
print(tab_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3.Créer un tableau de 10 valeurs initialisées à 25. 

In [101]:
tab_full=np.full(10,25)
print(tab_full)

[25 25 25 25 25 25 25 25 25 25]


4.Créer une matrice identité de taille 5 × 5

In [102]:
mat_identite=np.eye(5)
print(mat_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5.Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [103]:
tab_heures=np.arange(0,24)
print(tab_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6.Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [104]:
tab_valeurs=np.linspace(20,30,10)
print(tab_valeurs)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7.Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [105]:
np.random.seed(42)
tab_aleatoire=np.random.uniform(15,40,100)
print(tab_aleatoire)

[24.36350297 38.76785766 33.29984855 29.9664621  18.90046601 18.89986301
 16.4520903  36.65440364 30.02787529 32.70181444 15.51461236 39.2477463
 35.81106602 20.30847777 19.54562418 19.58511275 22.60605607 28.11891079
 25.79862547 22.2807285  30.29632237 18.48734652 22.30361621 24.15904608
 26.40174961 34.62939903 19.99184455 27.85586096 29.81036422 16.16126032
 30.1886213  19.26310309 16.62628982 38.72213843 39.14080083 35.2099337
 22.61534423 17.44180285 32.10582566 26.00381234 18.05095587 27.37942275
 15.85971303 37.73301005 21.46949954 31.56305711 22.7927769  28.00170053
 28.66775698 19.62136139 39.23961569 34.37832058 38.48747354 37.37068376
 29.94749947 38.04685588 17.21231255 19.89957156 16.13068222 23.13325827
 24.71693224 21.78372579 35.71843773 23.91883317 22.02336274 28.56740208
 18.52310562 35.05492452 16.86376609 39.67217342 34.30611923 19.96789204
 15.13805293 35.38653571 32.6714336  33.2251792  34.28175867 16.85111629
 23.96164321 17.89672649 36.57758565 30.58245317 23.2

Partie 3 – Exploration des tableaux 
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée 
2) Déterminer les propriétés suivantes du tableau :

    a.nombre de dimensions ; 

    b.nombre de valeurs ; 

    c.type des données ; 

    d.forme du tableau. 

1.Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [106]:
temperatures = np.random.randint(15, 45, 24)
print(temperatures)

[21 31 34 43 18 44 19 37 21 27 29 25 43 18 27 21 41 33 36 42 16 24 27 44]


2.Déterminer les propriétés suivantes du tableau :

 a.nombre de dimensions 

In [107]:
print("dimension du tableau : ", temperatures.ndim)

dimension du tableau :  1


b. nombre de valeurs 

In [108]:
print("Nombres de valeurs dans le tableau : ", temperatures.size)

Nombres de valeurs dans le tableau :  24


C.forme du tableau

In [109]:
print("Forme du tableau : ", temperatures.shape)

Forme du tableau :  (24,)


Partie 4 – Indexation et slicing 
Considérant le tableau représentant les 24 températures d'une journée, afficher : 
1) la première mesure ;  
2) la dernière mesure ;  
3) la température de 8h ;  
4) les températures de 8h à 12h ;  
5) les températures des 6 premières heures ;  
6) les températures des heures paires.

1.La premiere mesure

In [110]:
print("premiere mesure : ", temperatures[0])

premiere mesure :  21


2.la derniere mesure

In [111]:
print("derniere mesure : ", temperatures[-1])

derniere mesure :  44


3.La temperature de 8h

In [112]:
print("Température de 8 heures :", temperatures[7])

Température de 8 heures : 37


4.Les temperatures de 8h a 12h

In [113]:
print("les temperarures de 8h à 12h : ", temperatures[7:12])

les temperarures de 8h à 12h :  [37 21 27 29 25]


5.Les temperatures des 6 premieres heures

In [114]:
print("Les 6 premieres temeperatures : ", temperatures[:6])

Les 6 premieres temeperatures :  [21 31 34 43 18 44]


6.Les temperatures des heures paires

In [115]:
print("Les temperatures des heures paires : ", temperatures[::2])

Les temperatures des heures paires :  [21 34 18 19 21 29 43 27 41 36 16 27]


Partie 5 – Filtrage booléen 
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C 
2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C 
3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 
1/2 
4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

1.Afficher les températures supérieures à 30 °C 

In [116]:
temp_chaud = temperatures[temperatures > 30]
print(temp_chaud)

[31 34 43 44 37 43 41 33 36 42 44]


2.Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [117]:
temp_normal = temperatures [(temperatures > 20) & (temperatures < 30)]
print (temp_normal)

[21 21 27 29 25 27 21 24 27]


3. Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [118]:
anomalies = temperatures > 35
print (anomalies)
print (temperatures[anomalies])

[False False False  True False  True False  True False False False False
  True False False False  True False  True  True False False False  True]
[43 44 37 43 41 36 42 44]


4.Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

In [119]:
anom_sum=sum(anomalies)
print("NB anomalies:",anom_sum)

NB anomalies: 8


Partie 6 – Manipulation des dimensions 
On suppose qu’on a 5 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant 
une journée 
2) Transformer la matrice en un tableau unidimensionnel 
3) Déterminer la transposée de la matrice 
4) Extraire toutes les mesures du capteur 1 ; 
5) Extraire toutes les mesures du capteur 5 ; 
6) Extraire les mesures de tous les capteurs à 10h ; 
7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

1.Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant 
une journée 

In [120]:
temperatures_bat1 = np.random.randint(15, 46, (5, 24))

print(temperatures_bat1)
print(temperatures_bat1.shape)

[[39 35 20 42 42 26 26 34 44 44 25 40 37 42 39 21 44 15 15 39 41 44 39 34]
 [27 23 17 21 20 22 41 23 44 19 15 33 24 26 38 29 41 36 38 23 34 31 44 31]
 [40 34 26 44 21 16 17 31 19 31 38 31 41 31 16 16 42 36 37 19 15 15 33 44]
 [16 35 26 40 20 37 18 37 25 38 41 31 45 20 38 19 34 16 20 36 25 45 30 30]
 [15 23 42 41 20 30 43 17 34 42 41 18 33 40 17 45 33 34 21 34 23 15 22 21]]
(5, 24)


2. Transformer la matrice en un tableau unidimensionnel

In [121]:
temperatures_1d = temperatures_bat1.flatten()

print(temperatures_1d)

[39 35 20 42 42 26 26 34 44 44 25 40 37 42 39 21 44 15 15 39 41 44 39 34
 27 23 17 21 20 22 41 23 44 19 15 33 24 26 38 29 41 36 38 23 34 31 44 31
 40 34 26 44 21 16 17 31 19 31 38 31 41 31 16 16 42 36 37 19 15 15 33 44
 16 35 26 40 20 37 18 37 25 38 41 31 45 20 38 19 34 16 20 36 25 45 30 30
 15 23 42 41 20 30 43 17 34 42 41 18 33 40 17 45 33 34 21 34 23 15 22 21]


3.Déterminer la transposée de la matrice 

In [122]:
temperatures_transposee = temperatures_bat1.T

print(temperatures_transposee)
print(temperatures_transposee.shape)

[[39 27 40 16 15]
 [35 23 34 35 23]
 [20 17 26 26 42]
 [42 21 44 40 41]
 [42 20 21 20 20]
 [26 22 16 37 30]
 [26 41 17 18 43]
 [34 23 31 37 17]
 [44 44 19 25 34]
 [44 19 31 38 42]
 [25 15 38 41 41]
 [40 33 31 31 18]
 [37 24 41 45 33]
 [42 26 31 20 40]
 [39 38 16 38 17]
 [21 29 16 19 45]
 [44 41 42 34 33]
 [15 36 36 16 34]
 [15 38 37 20 21]
 [39 23 19 36 34]
 [41 34 15 25 23]
 [44 31 15 45 15]
 [39 44 33 30 22]
 [34 31 44 30 21]]
(24, 5)


4.Extraire toutes les mesures du capteur 1 

In [123]:
capteur1 = temperatures_bat1[0, :]

print(capteur1)

[39 35 20 42 42 26 26 34 44 44 25 40 37 42 39 21 44 15 15 39 41 44 39 34]


5.Extraire toutes les mesures du capteur 5 

In [124]:
capteur5 = temperatures_bat1[4, :]

print(capteur5)

[15 23 42 41 20 30 43 17 34 42 41 18 33 40 17 45 33 34 21 34 23 15 22 21]


6. Extraire les mesures de tous les capteurs à 10h 

In [125]:
mesures_10h = temperatures_bat1[:, 10]

print(mesures_10h)

[25 15 38 41 41]


7.Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

In [126]:
mesures = temperatures_bat1[1:4, 8:13]

print(mesures)

[[44 19 15 33 24]
 [19 31 38 31 41]
 [25 38 41 31 45]]


Partie 7 – Concaténation 
On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs 
durant une journée 
2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée 

1.Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs 
durant une journée

In [127]:
temperatures_bat2 = np.random.randint(15, 45, (3, 24))

print(temperatures_bat2)

[[32 22 15 25 42 39 39 32 37 44 24 17 21 42 30 40 30 39 34 42 31 16 15 30]
 [44 26 19 19 41 37 23 23 17 33 30 30 17 34 38 36 38 15 38 34 25 31 22 18]
 [20 22 34 44 17 30 44 39 17 39 43 32 28 32 16 36 17 30 43 23 18 15 18 15]]


2.Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée 

In [128]:
temperatures_8 = np.concatenate((temperatures_bat1, temperatures_bat2), axis=0)

print(temperatures_8)
print(temperatures_8.shape)

[[39 35 20 42 42 26 26 34 44 44 25 40 37 42 39 21 44 15 15 39 41 44 39 34]
 [27 23 17 21 20 22 41 23 44 19 15 33 24 26 38 29 41 36 38 23 34 31 44 31]
 [40 34 26 44 21 16 17 31 19 31 38 31 41 31 16 16 42 36 37 19 15 15 33 44]
 [16 35 26 40 20 37 18 37 25 38 41 31 45 20 38 19 34 16 20 36 25 45 30 30]
 [15 23 42 41 20 30 43 17 34 42 41 18 33 40 17 45 33 34 21 34 23 15 22 21]
 [32 22 15 25 42 39 39 32 37 44 24 17 21 42 30 40 30 39 34 42 31 16 15 30]
 [44 26 19 19 41 37 23 23 17 33 30 30 17 34 38 36 38 15 38 34 25 31 22 18]
 [20 22 34 44 17 30 44 39 17 39 43 32 28 32 16 36 17 30 43 23 18 15 18 15]]
(8, 24)


In [129]:
temperatures_8 = np.vstack((temperatures_bat1, temperatures_bat2))

print(temperatures_8)
print(temperatures_8.shape)

[[39 35 20 42 42 26 26 34 44 44 25 40 37 42 39 21 44 15 15 39 41 44 39 34]
 [27 23 17 21 20 22 41 23 44 19 15 33 24 26 38 29 41 36 38 23 34 31 44 31]
 [40 34 26 44 21 16 17 31 19 31 38 31 41 31 16 16 42 36 37 19 15 15 33 44]
 [16 35 26 40 20 37 18 37 25 38 41 31 45 20 38 19 34 16 20 36 25 45 30 30]
 [15 23 42 41 20 30 43 17 34 42 41 18 33 40 17 45 33 34 21 34 23 15 22 21]
 [32 22 15 25 42 39 39 32 37 44 24 17 21 42 30 40 30 39 34 42 31 16 15 30]
 [44 26 19 19 41 37 23 23 17 33 30 30 17 34 38 36 38 15 38 34 25 31 22 18]
 [20 22 34 44 17 30 44 39 17 39 43 32 28 32 16 36 17 30 43 23 18 15 18 15]]
(8, 24)


Partie 8 : Calcul scientifique 
Considérons le tableau représentant les 24 températures du 1er bâtiment. 
1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la 
variance et l’écart-type 
2) Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart
type du tableau standardisé 
3) Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé 
4) Convertir le tableau initial en Fahrenheit 

1.Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la 
variance et l’écart-type 

In [130]:
min = temperatures.min()
print("Température minimale : ", min)

max = temperatures.max()
print("Température maximale : ", max)

somme = temperatures.sum()
print("Somme des températures : ", somme)

moy = temperatures.mean()
print("Température moyenne : ", moy)

mediane = np.median(temperatures)
print("Température médiane : ", mediane)

variance = np.var(temperatures)
print("Variance des températures : ", variance)

ecart_type = np.std(temperatures)
print("Écart type des températures : ", ecart_type)


Température minimale :  16
Température maximale :  44
Somme des températures :  721
Température moyenne :  30.041666666666668
Température médiane :  28.0
Variance des températures :  85.1232638888889
Écart type des températures :  9.226226958453218


2.Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart
type du tableau standardisé

In [131]:
temp_standard=(temperatures - moy) / ecart_type
print("Températures standardisées : ", temp_standard)

moy_standard=temp_standard.mean()
print("Moyenne des températures standardisées : ", moy_standard)

ecart_type_standard=np.std(temp_standard)
print("Écart type des températures standardisées : ", ecart_type_standard)

Températures standardisées :  [-0.97999612  0.10387056  0.42903056  1.40451058 -1.30515613  1.51289724
 -1.19676946  0.75419057 -0.97999612 -0.32967612 -0.11290278 -0.54644945
  1.40451058 -1.30515613 -0.32967612 -0.97999612  1.18773724  0.32064389
  0.6458039   1.29612391 -1.52192947 -0.65483612 -0.32967612  1.51289724]
Moyenne des températures standardisées :  -1.4802973661668753e-16
Écart type des températures standardisées :  0.9999999999999998


3.Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé

In [132]:
temp_normalise=(temperatures - min) / (max - min)
print("Températures normalisées : ", temp_normalise)

Températures normalisées :  [0.17857143 0.53571429 0.64285714 0.96428571 0.07142857 1.
 0.10714286 0.75       0.17857143 0.39285714 0.46428571 0.32142857
 0.96428571 0.07142857 0.39285714 0.17857143 0.89285714 0.60714286
 0.71428571 0.92857143 0.         0.28571429 0.39285714 1.        ]


4.Convertir le tableau initial en Fahrenheit 

In [133]:
temp_fahrenheit = (temperatures * 9/5) + 32
print("Températures en Fahrenheit : ", temp_fahrenheit)

Températures en Fahrenheit :  [ 69.8  87.8  93.2 109.4  64.4 111.2  66.2  98.6  69.8  80.6  84.2  77.
 109.4  64.4  80.6  69.8 105.8  91.4  96.8 107.6  60.8  75.2  80.6 111.2]


Partie 9 : Broadcasting 
1) Créer aléatoirement la matrice temperatures_vsd représentant les températures mesurées un 
vendredi, un samedi et un dimanche successifs, dans le 2nd bâtiment 
2) Supposons que les valeurs de calibration des capteurs soient stockées dans le tableau  
correction = np.array([1, -0.5, 0.2]) 
Appliquer automatiquement les corrections pour trouver les mesures corrigées 
mesures_corrigees = temperatures_vsd + correction

1.Créer aléatoirement la matrice temperatures_vsd représentant les températures mesurées un 
vendredi, un samedi et un dimanche successifs, dans le 2nd bâtiment 

In [137]:
np.random.seed(42)

temperatures_vsd = np.random.randint(15, 45, (3, 24, 3))

print(temperatures_vsd)
print(temperatures_vsd.shape)

[[[21 34 43]
  [29 25 22]
  [43 35 21]
  [40 33 37]
  [25 25 38]
  [35 18 22]
  [38 17 36]
  [35 16 38]
  [26 44 20]
  [16 42 35]
  [15 26 40]
  [36 43 26]
  [39 31 41]
  [41 24 42]
  [42 30 29]
  [44 44 29]
  [44 33 26]
  [37 34 39]
  [17 19 33]
  [21 35 23]
  [21 32 18]
  [39 42 28]
  [32 40 23]
  [40 35 16]]

 [[34 42 29]
  [42 21 26]
  [43 22 29]
  [17 28 31]
  [18 32 22]
  [18 16 44]
  [20 36 24]
  [18 36 43]
  [32 40 26]
  [16 24 44]
  [18 28 30]
  [29 22 28]
  [37 42 39]
  [44 22 35]
  [30 27 32]
  [29 35 38]
  [40 39 42]
  [42 42 27]
  [23 43 29]
  [27 15 39]
  [21 23 38]
  [15 26 22]
  [38 25 33]
  [31 22 17]]

 [[17 15 41]
  [19 24 21]
  [40 23 42]
  [21 23 22]
  [26 16 15]
  [30 37 37]
  [44 38 19]
  [17 26 22]
  [36 41 17]
  [15 17 19]
  [29 28 17]
  [15 19 40]
  [37 28 21]
  [41 23 29]
  [29 40 24]
  [42 27 33]
  [21 31 34]
  [43 18 44]
  [19 37 21]
  [27 29 25]
  [43 18 27]
  [21 41 33]
  [36 42 16]
  [24 27 44]]]
(3, 24, 3)


2.Supposons que les valeurs de calibration des capteurs soient stockées dans le tableau  
correction = np.array([1, -0.5, 0.2]) 
Appliquer automatiquement les corrections pour trouver les mesures corrigées 
mesures_corrigees = temperatures_vsd + correction

In [138]:
correction=np.array([1,-0.5,0.2])
mesures_corrigees = temperatures_vsd + correction
print(mesures_corrigees)

[[[22.  33.5 43.2]
  [30.  24.5 22.2]
  [44.  34.5 21.2]
  [41.  32.5 37.2]
  [26.  24.5 38.2]
  [36.  17.5 22.2]
  [39.  16.5 36.2]
  [36.  15.5 38.2]
  [27.  43.5 20.2]
  [17.  41.5 35.2]
  [16.  25.5 40.2]
  [37.  42.5 26.2]
  [40.  30.5 41.2]
  [42.  23.5 42.2]
  [43.  29.5 29.2]
  [45.  43.5 29.2]
  [45.  32.5 26.2]
  [38.  33.5 39.2]
  [18.  18.5 33.2]
  [22.  34.5 23.2]
  [22.  31.5 18.2]
  [40.  41.5 28.2]
  [33.  39.5 23.2]
  [41.  34.5 16.2]]

 [[35.  41.5 29.2]
  [43.  20.5 26.2]
  [44.  21.5 29.2]
  [18.  27.5 31.2]
  [19.  31.5 22.2]
  [19.  15.5 44.2]
  [21.  35.5 24.2]
  [19.  35.5 43.2]
  [33.  39.5 26.2]
  [17.  23.5 44.2]
  [19.  27.5 30.2]
  [30.  21.5 28.2]
  [38.  41.5 39.2]
  [45.  21.5 35.2]
  [31.  26.5 32.2]
  [30.  34.5 38.2]
  [41.  38.5 42.2]
  [43.  41.5 27.2]
  [24.  42.5 29.2]
  [28.  14.5 39.2]
  [22.  22.5 38.2]
  [16.  25.5 22.2]
  [39.  24.5 33.2]
  [32.  21.5 17.2]]

 [[18.  14.5 41.2]
  [20.  23.5 21.2]
  [41.  22.5 42.2]
  [22.  22.5 22.2]
  [27.  

Partie 10 : Bonus 
Proposer et réaliser toute fonctionnalité pertinente et utile qu’on pourrait rajouter à l’application.

Créons un tableau aléatoire qui correspond aux valeurs des 8 capteurs pour 3 jours (VSD) et comptons le nombre d'anomalies (température > 35 ) pour chaque jour et chaque capteur

In [ ]:
temperatures_bat1_vsd = np.random.randint(15, 45, (5, 24, 3))
temperatures_bat2_vsd = np.random.randint(15, 45, (3, 24, 3))

temperatures_8_vsd = np.concatenate(
    (temperatures_bat1_vsd, temperatures_bat2_vsd),
    axis=0
)

anomalies_8 = temperatures_8_vsd > 35
nombre_anomalies_8 = np.sum(anomalies_8, axis=1)


Générons un rapport qui condense ces  resultats

In [141]:
jours = ["Vendredi", "Samedi", "Dimanche"]

print("========== RAPPORT DE TEMPÉRATURE ==========")

for capteur in range(8):

    if capteur < 5:
        batiment = "Bâtiment 1"
    else:
        batiment = "Bâtiment 2"

    print(f"\n{batiment} - Capteur {capteur + 1}")

    for jour in range(3):
        print(
            f"  {jours[jour]} : "
            f"{nombre_anomalies_8[capteur, jour]} anomalie(s)"
        )

========== RAPPORT DE TEMPÉRATURE ==========

Bâtiment 1 - Capteur 1
  Vendredi : 7 anomalie(s)
  Samedi : 5 anomalie(s)
  Dimanche : 8 anomalie(s)

Bâtiment 1 - Capteur 2
  Vendredi : 10 anomalie(s)
  Samedi : 7 anomalie(s)
  Dimanche : 9 anomalie(s)

Bâtiment 1 - Capteur 3
  Vendredi : 10 anomalie(s)
  Samedi : 4 anomalie(s)
  Dimanche : 4 anomalie(s)

Bâtiment 1 - Capteur 4
  Vendredi : 4 anomalie(s)
  Samedi : 12 anomalie(s)
  Dimanche : 8 anomalie(s)

Bâtiment 1 - Capteur 5
  Vendredi : 10 anomalie(s)
  Samedi : 7 anomalie(s)
  Dimanche : 9 anomalie(s)

Bâtiment 2 - Capteur 6
  Vendredi : 9 anomalie(s)
  Samedi : 10 anomalie(s)
  Dimanche : 4 anomalie(s)

Bâtiment 2 - Capteur 7
  Vendredi : 12 anomalie(s)
  Samedi : 9 anomalie(s)
  Dimanche : 3 anomalie(s)

Bâtiment 2 - Capteur 8
  Vendredi : 6 anomalie(s)
  Samedi : 5 anomalie(s)
  Dimanche : 4 anomalie(s)
