Partie 1 : Listes Python vs tableaux NumPy 
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 
1) Créer une liste Python stockant ces températures; 
2) Créer un tableau NumPy équivalent stockant ces températures ; 
3) Effectuer une multiplication par 2 sur ces deux collections; 
4) Quelle différence observe-t-on ? 

In [3]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.8 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.6 MB 5.2 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 5.6 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 5.9 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 5.9 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.6 MB 6.6 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.7 MB/s  0:00:02
Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

1.CREATION DE LISTE PYTHON 

In [ ]:
Liste_temperature = [24.5 , 25.1 , 26.3 , 27.0 , 25.8 ]


2.CREATION DE TABLEAU NUMPY

In [ ]:
tab_temp=np.array(Liste_temperature)

3.MULTIPLICATION DES DEUX PAR "2"

In [10]:
Liste_temperature= Liste_temperature*2
print(Liste_temperature)

tab_temp=tab_temp*2
print(tab_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


4.OBSERVATION

La différence observée se situe principalement au niveau des résultats. La multiplication par 2 double la liste et donne un tableau où chaque élément est multiplié par 2.


Partie 2 – Création des données 
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 
2) Créer un tableau contenant 10 valeurs égales à 1. 
3) Créer un tableau de 10 valeurs initialisées à 25. 
4) Créer une matrice identité de taille 5 × 5. 
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

1. Creer un tableau representant les mesures de température de 10 capteurs , initialement à zero


In [11]:
tab_zero=np.zeros(10)
print(tab_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.Créer un tableau contenant 10 valeurs égales à 1. 

In [12]:
tab_one=np.ones(10)
print(tab_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3.Créer un tableau de 10 valeurs initialisées à 25. 

In [13]:
tab_full=np.full(10,25)
print(tab_full)

[25 25 25 25 25 25 25 25 25 25]


4.Créer une matrice identité de taille 5 × 5

In [14]:
mat_identite=np.eye(5)
print(mat_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5.Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [15]:
tab_heures=np.arange(0,24)
print(tab_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6.Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [16]:
tab_valeurs=np.linspace(20,30,10)
print(tab_valeurs)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7.Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [18]:
np.random.seed(42)
tab_aleatoire=np.random.rand(100)
print(tab_aleatoire)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
 0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
 0.59789998 0.92187424 0.0884925  0.19598286 0.04522729 0.32533033
 0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477 0.19871568
 0.00552212 0.81546143 0.70685734 0.72900717 0.77127035 0.07404465
 0.35846573 0.11586906 0.86310343 0.62329813 0.33089802 0.06355835
 0.31098232 0.32518332 0.72960618 0.63755747 0.88721274 0.4722