Partie 1 : Listes Python vs tableaux NumPy 
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 
1) Créer une liste Python stockant ces températures; 
2) Créer un tableau NumPy équivalent stockant ces températures ; 
3) Effectuer une multiplication par 2 sur ces deux collections; 
4) Quelle différence observe-t-on ? 

In [ ]:
%pip install numpy

In [8]:
import numpy as np

1.CREATION DE LISTE PYTHON 

In [ ]:
Liste_temperature = [24.5 , 25.1 , 26.3 , 27.0 , 25.8 ]


2.CREATION DE TABLEAU NUMPY

In [ ]:
tab_temp=np.array(Liste_temperature)

3.MULTIPLICATION DES DEUX PAR "2"

In [10]:
Liste_temperature= Liste_temperature*2
print(Liste_temperature)

tab_temp=tab_temp*2
print(tab_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


4.OBSERVATION

La différence observée se situe principalement au niveau des résultats. La multiplication par 2 double la liste et donne un tableau où chaque élément est multiplié par 2.


Partie 2 – Création des données 
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 
2) Créer un tableau contenant 10 valeurs égales à 1. 
3) Créer un tableau de 10 valeurs initialisées à 25. 
4) Créer une matrice identité de taille 5 × 5. 
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

1. Creer un tableau representant les mesures de température de 10 capteurs , initialement à zero


In [11]:
tab_zero=np.zeros(10)
print(tab_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.Créer un tableau contenant 10 valeurs égales à 1. 

In [12]:
tab_one=np.ones(10)
print(tab_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3.Créer un tableau de 10 valeurs initialisées à 25. 

In [13]:
tab_full=np.full(10,25)
print(tab_full)

[25 25 25 25 25 25 25 25 25 25]


4.Créer une matrice identité de taille 5 × 5

In [14]:
mat_identite=np.eye(5)
print(mat_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5.Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [15]:
tab_heures=np.arange(0,24)
print(tab_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6.Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [16]:
tab_valeurs=np.linspace(20,30,10)
print(tab_valeurs)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7.Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [ ]:
np.random.seed(42)
tab_aleatoire=np.random.uniform(15,40,100)
print(tab_aleatoire)

Partie 3 – Exploration des tableaux 
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée 
2) Déterminer les propriétés suivantes du tableau :

    a.nombre de dimensions ; 

    b.nombre de valeurs ; 

    c.type des données ; 

    d.forme du tableau. 

1.Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [37]:
temperatures = np.random.randint(15, 45, 24)
print(temperatures)

[22 21 32 22 15 25 42 39 39 32 37 44 24 17 21 42 30 40 30 39 34 42 31 16]


2.Déterminer les propriétés suivantes du tableau :

 a.nombre de dimensions 

In [38]:
print("dimension du tableau : ", temperatures.ndim)

dimension du tableau :  1


b. nombre de valeurs 

In [39]:
print("Nombres de valeurs dans le tableau : ", temperatures.size)

Nombres de valeurs dans le tableau :  24


C.forme du tableau

In [40]:
print("Forme du tableau : ", temperatures.shape)

Forme du tableau :  (24,)


Partie 4 – Indexation et slicing 
Considérant le tableau représentant les 24 températures d'une journée, afficher : 
1) la première mesure ;  
2) la dernière mesure ;  
3) la température de 8h ;  
4) les températures de 8h à 12h ;  
5) les températures des 6 premières heures ;  
6) les températures des heures paires.

1.La premiere mesure

In [41]:
print("premiere mesure : ", temperatures[0])

premiere mesure :  22


2.la derniere mesure

In [42]:
print("derniere mesure : ", temperatures[-1])

derniere mesure :  16


3.La temperature de 8h

In [43]:
print("Température de 8 heures :", temperatures[7])

Température de 8 heures : 39


4.Les temperatures de 8h a 12h

In [44]:
print("les temperarures de 8h à 12h : ", temperatures[7:12])

les temperarures de 8h à 12h :  [39 39 32 37 44]


5.Les temperatures des 6 premieres heures

In [45]:
print("Les 6 premieres temeperatures : ", temperatures[:6])

Les 6 premieres temeperatures :  [22 21 32 22 15 25]


6.Les temperatures des heures paires

In [46]:
print("Les temperatures des heures paires : ", temperatures[::2])

Les temperatures des heures paires :  [22 32 15 42 39 37 24 21 30 30 34 31]


Partie 5 – Filtrage booléen 
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C 
2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C 
3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 
1/2 
4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

1.Afficher les températures supérieures à 30 °C 

In [48]:
temp_chaud = temperatures[temperatures > 30]
print(temp_chaud)

[32 42 39 39 32 37 44 42 40 39 34 42 31]


2.Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [54]:
temp_normal = temperatures [(temperatures > 20) & (temperatures < 30)]
print (temp_normal)

[22 21 22 25 24 21]


3. Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [56]:
anomalies = temperatures > 35
print (anomalies)
print (temperatures[anomalies])

[False False False False False False  True  True  True False  True  True
 False False False  True False  True False  True False  True False False]
[42 39 39 37 44 42 40 39 42]


4.Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

In [57]:
anom_sum=sum(anomalies)
print("NB anomalies:",anom_sum)

NB anomalies: 9


Partie 6 – Manipulation des dimensions 
On suppose qu’on a 5 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant 
une journée 
2) Transformer la matrice en un tableau unidimensionnel 
3) Déterminer la transposée de la matrice 
4) Extraire toutes les mesures du capteur 1 ; 
5) Extraire toutes les mesures du capteur 5 ; 
6) Extraire les mesures de tous les capteurs à 10h ; 
7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

1.Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant 
une journée 

In [63]:
temperatures = np.random.randint(15, 46, (5, 24))

print(temperatures)
print(temperatures.shape)

[[40 37 42 39 21 44 15 15 39 41 44 39 34 27 23 17 21 20 22 41 23 44 19 15]
 [33 24 26 38 29 41 36 38 23 34 31 44 31 40 34 26 44 21 16 17 31 19 31 38]
 [31 41 31 16 16 42 36 37 19 15 15 33 44 16 35 26 40 20 37 18 37 25 38 41]
 [31 45 20 38 19 34 16 20 36 25 45 30 30 15 23 42 41 20 30 43 17 34 42 41]
 [18 33 40 17 45 33 34 21 34 23 15 22 21 32 22 15 25 42 39 39 32 37 45 44]]
(5, 24)


2. Transformer la matrice en un tableau unidimensionnel

In [64]:
temperatures_1d = temperatures.flatten()

print(temperatures_1d)

[40 37 42 39 21 44 15 15 39 41 44 39 34 27 23 17 21 20 22 41 23 44 19 15
 33 24 26 38 29 41 36 38 23 34 31 44 31 40 34 26 44 21 16 17 31 19 31 38
 31 41 31 16 16 42 36 37 19 15 15 33 44 16 35 26 40 20 37 18 37 25 38 41
 31 45 20 38 19 34 16 20 36 25 45 30 30 15 23 42 41 20 30 43 17 34 42 41
 18 33 40 17 45 33 34 21 34 23 15 22 21 32 22 15 25 42 39 39 32 37 45 44]


3.Déterminer la transposée de la matrice 

In [65]:
temperatures_transposee = temperatures.T

print(temperatures_transposee)
print(temperatures_transposee.shape)

[[40 33 31 31 18]
 [37 24 41 45 33]
 [42 26 31 20 40]
 [39 38 16 38 17]
 [21 29 16 19 45]
 [44 41 42 34 33]
 [15 36 36 16 34]
 [15 38 37 20 21]
 [39 23 19 36 34]
 [41 34 15 25 23]
 [44 31 15 45 15]
 [39 44 33 30 22]
 [34 31 44 30 21]
 [27 40 16 15 32]
 [23 34 35 23 22]
 [17 26 26 42 15]
 [21 44 40 41 25]
 [20 21 20 20 42]
 [22 16 37 30 39]
 [41 17 18 43 39]
 [23 31 37 17 32]
 [44 19 25 34 37]
 [19 31 38 42 45]
 [15 38 41 41 44]]
(24, 5)


4.Extraire toutes les mesures du capteur 1 

In [66]:
capteur1 = temperatures[0, :]

print(capteur1)

[40 37 42 39 21 44 15 15 39 41 44 39 34 27 23 17 21 20 22 41 23 44 19 15]


5.Extraire toutes les mesures du capteur 5 

In [67]:
capteur5 = temperatures[4, :]

print(capteur5)

[18 33 40 17 45 33 34 21 34 23 15 22 21 32 22 15 25 42 39 39 32 37 45 44]


6. Extraire les mesures de tous les capteurs à 10h 

In [68]:
mesures_10h = temperatures[:, 10]

print(mesures_10h)

[44 31 15 45 15]


7.Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

In [69]:
mesures = temperatures[1:4, 8:13]

print(mesures)

[[23 34 31 44 31]
 [19 15 15 33 44]
 [36 25 45 30 30]]


Partie 7 – Concaténation 
On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs 
durant une journée 
2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée 

1.Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs 
durant une journée

In [70]:
temperatures_bat2 = np.random.randint(15, 45, (3, 24))

print(temperatures_bat2)

[[24 17 21 42 30 40 30 39 34 42 31 16 15 30 44 26 19 19 41 37 23 23 17 33]
 [30 30 17 34 38 36 38 15 38 34 25 31 22 18 20 22 34 44 17 30 44 39 17 39]
 [43 32 28 32 16 36 17 30 43 23 18 15 18 15 28 35 30 34 38 22 21 17 31 15]]


2.Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée 

In [71]:
temperatures_8 = np.concatenate((temperatures, temperatures_bat2), axis=0)

print(temperatures_8)
print(temperatures_8.shape)

[[40 37 42 39 21 44 15 15 39 41 44 39 34 27 23 17 21 20 22 41 23 44 19 15]
 [33 24 26 38 29 41 36 38 23 34 31 44 31 40 34 26 44 21 16 17 31 19 31 38]
 [31 41 31 16 16 42 36 37 19 15 15 33 44 16 35 26 40 20 37 18 37 25 38 41]
 [31 45 20 38 19 34 16 20 36 25 45 30 30 15 23 42 41 20 30 43 17 34 42 41]
 [18 33 40 17 45 33 34 21 34 23 15 22 21 32 22 15 25 42 39 39 32 37 45 44]
 [24 17 21 42 30 40 30 39 34 42 31 16 15 30 44 26 19 19 41 37 23 23 17 33]
 [30 30 17 34 38 36 38 15 38 34 25 31 22 18 20 22 34 44 17 30 44 39 17 39]
 [43 32 28 32 16 36 17 30 43 23 18 15 18 15 28 35 30 34 38 22 21 17 31 15]]
(8, 24)


In [72]:
temperatures_8 = np.vstack((temperatures, temperatures_bat2))

print(temperatures_8)
print(temperatures_8.shape)

[[40 37 42 39 21 44 15 15 39 41 44 39 34 27 23 17 21 20 22 41 23 44 19 15]
 [33 24 26 38 29 41 36 38 23 34 31 44 31 40 34 26 44 21 16 17 31 19 31 38]
 [31 41 31 16 16 42 36 37 19 15 15 33 44 16 35 26 40 20 37 18 37 25 38 41]
 [31 45 20 38 19 34 16 20 36 25 45 30 30 15 23 42 41 20 30 43 17 34 42 41]
 [18 33 40 17 45 33 34 21 34 23 15 22 21 32 22 15 25 42 39 39 32 37 45 44]
 [24 17 21 42 30 40 30 39 34 42 31 16 15 30 44 26 19 19 41 37 23 23 17 33]
 [30 30 17 34 38 36 38 15 38 34 25 31 22 18 20 22 34 44 17 30 44 39 17 39]
 [43 32 28 32 16 36 17 30 43 23 18 15 18 15 28 35 30 34 38 22 21 17 31 15]]
(8, 24)


Partie 8 : Calcul scientifique 
Considérons le tableau représentant les 24 températures du 1er bâtiment. 
1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la 
variance et l’écart-type 
2) Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart
type du tableau standardisé 
3) Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé 
4) Convertir le tableau initial en Fahrenheit 

1.Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la 
variance et l’écart-type 

In [ ]:
min = temperatures.min()
print("Température minimale : ", min)

max = temperatures.max()
print("Température maximale : ", max)

