Partie 1 : Listes Python vs tableaux NumPy 
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 
1) Créer une liste Python stockant ces températures; 
2) Créer un tableau NumPy équivalent stockant ces températures ; 
3) Effectuer une multiplication par 2 sur ces deux collections; 
4) Quelle différence observe-t-on ? 

In [ ]:
%pip install numpy

In [8]:
import numpy as np

1.CREATION DE LISTE PYTHON 

In [ ]:
Liste_temperature = [24.5 , 25.1 , 26.3 , 27.0 , 25.8 ]


2.CREATION DE TABLEAU NUMPY

In [ ]:
tab_temp=np.array(Liste_temperature)

3.MULTIPLICATION DES DEUX PAR "2"

In [10]:
Liste_temperature= Liste_temperature*2
print(Liste_temperature)

tab_temp=tab_temp*2
print(tab_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


4.OBSERVATION

La différence observée se situe principalement au niveau des résultats. La multiplication par 2 double la liste et donne un tableau où chaque élément est multiplié par 2.


Partie 2 – Création des données 
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 
2) Créer un tableau contenant 10 valeurs égales à 1. 
3) Créer un tableau de 10 valeurs initialisées à 25. 
4) Créer une matrice identité de taille 5 × 5. 
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

1. Creer un tableau representant les mesures de température de 10 capteurs , initialement à zero


In [11]:
tab_zero=np.zeros(10)
print(tab_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.Créer un tableau contenant 10 valeurs égales à 1. 

In [12]:
tab_one=np.ones(10)
print(tab_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3.Créer un tableau de 10 valeurs initialisées à 25. 

In [13]:
tab_full=np.full(10,25)
print(tab_full)

[25 25 25 25 25 25 25 25 25 25]


4.Créer une matrice identité de taille 5 × 5

In [14]:
mat_identite=np.eye(5)
print(mat_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5.Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [15]:
tab_heures=np.arange(0,24)
print(tab_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6.Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [16]:
tab_valeurs=np.linspace(20,30,10)
print(tab_valeurs)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7.Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [ ]:
np.random.seed(42)
tab_aleatoire=np.random.uniform(15,40,100)
print(tab_aleatoire)

Partie 3 – Exploration des tableaux 
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée 
2) Déterminer les propriétés suivantes du tableau :

    a.nombre de dimensions ; 

    b.nombre de valeurs ; 

    c.type des données ; 

    d.forme du tableau. 

1.Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [37]:
temperatures = np.random.randint(15, 45, 24)
print(temperatures)

[22 21 32 22 15 25 42 39 39 32 37 44 24 17 21 42 30 40 30 39 34 42 31 16]


2.Déterminer les propriétés suivantes du tableau :

 a.nombre de dimensions 

In [38]:
print("dimension du tableau : ", temperatures.ndim)

dimension du tableau :  1


b. nombre de valeurs 

In [39]:
print("Nombres de valeurs dans le tableau : ", temperatures.size)

Nombres de valeurs dans le tableau :  24


C.forme du tableau

In [40]:
print("Forme du tableau : ", temperatures.shape)

Forme du tableau :  (24,)


Partie 4 – Indexation et slicing 
Considérant le tableau représentant les 24 températures d'une journée, afficher : 
1) la première mesure ;  
2) la dernière mesure ;  
3) la température de 8h ;  
4) les températures de 8h à 12h ;  
5) les températures des 6 premières heures ;  
6) les températures des heures paires.

1.La premiere mesure

In [41]:
print("premiere mesure : ", temperatures[0])

premiere mesure :  22


2.la derniere mesure

In [42]:
print("derniere mesure : ", temperatures[-1])

derniere mesure :  16


3.La temperature de 8h

In [43]:
print("Température de 8 heures :", temperatures[7])

Température de 8 heures : 39


4.Les temperatures de 8h a 12h

In [44]:
print("les temperarures de 8h à 12h : ", temperatures[7:12])

les temperarures de 8h à 12h :  [39 39 32 37 44]


5.Les temperatures des 6 premieres heures

In [45]:
print("Les 6 premieres temeperatures : ", temperatures[:6])

Les 6 premieres temeperatures :  [22 21 32 22 15 25]


6.Les temperatures des heures paires

In [46]:
print("Les temperatures des heures paires : ", temperatures[::2])

Les temperatures des heures paires :  [22 32 15 42 39 37 24 21 30 30 34 31]


Partie 5 – Filtrage booléen 
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C 
2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C 
3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 
1/2 
4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

1.Afficher les températures supérieures à 30 °C 

In [48]:
temp_chaud = temperatures[temperatures > 30]
print(temp_chaud)

[32 42 39 39 32 37 44 42 40 39 34 42 31]


2.Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [54]:
temp_normal = temperatures [(temperatures > 20) & (temperatures < 30)]
print (temp_normal)

[22 21 22 25 24 21]


3. Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [56]:
anomalies = temperatures > 35
print (anomalies)
print (temperatures[anomalies])

[False False False False False False  True  True  True False  True  True
 False False False  True False  True False  True False  True False False]
[42 39 39 37 44 42 40 39 42]


4.Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

In [57]:
anom_sum=sum(anomalies)
print("NB anomalies:",anom_sum)

NB anomalies: 9
